spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/auth_service?useUniqueCode=true&characterEncoding=utf-8
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  application:
    name: auth-service
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8801
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true