# 登陆时转发到auth-service
# 其他请求通过过滤器鉴定token是否有权限
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
#          filters:
#            - StripPrefix=1
        - id: file_route
          uri: lb://file-service
          predicates:
            - Path=/file/**
#          filters:
#            - StripPrefix=1
        - id: user_route
          uri: http://localhost:8811
          predicates:
            - Path=/user/**, /province/**, /address/**
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/product/**
#          filters:
#            - StripPrefix=1
        - id: order_route
          uri: lb://order-service
          predicates:
            - Path=/order/**
#          filters:
#            - StripPrefix=1
        - id: payment_route
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
#          filters:
#            - StripPrefix=1
      default-filters:
        - StripPrefix=1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka