spring:
  application:
    name: file-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-request-size: 50MB
      max-file-size: 10MB
server:
  port: 8901
eureka:
  client:
    service-url:
      defaultZone: http://8.210.31.133:8761/eureka/, http://8.210.31.133:8762/eureka/
  instance:
    prefer-ip-address: true
