spring:
  datasource:
    url: jdbc:mysql://106.15.230.133:3306/user_service?useUniqueCode=true&characterEncoding=utf-8
    username: root
    password: LImy0501#+
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  application:
    name: user-service
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8811
eureka:
  client:
    service-url:
      defaultZone: http://8.210.31.133:8761/eureka/, http://8.210.31.133:8762/eureka/
  instance:
    prefer-ip-address: true