spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_service?useUniqueCode=true&characterEncoding=utf-8
    username: root
    password: rootpwd
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8811
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: true