spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/products?maxPoolSize=256
server:
  port: 8821
logging:
  level:
    com.lee.productservice: debug