spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://test:testpwd@106.15.230.133:27017/product?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
server:
  port: 8821
logging:
  level:
    com.lee.productservice: debug