spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/products
      username: user
      password: password
server:
  port: 8821
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/