eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka, http://peer2:8762/eureka
---
spring:
  profiles: peer1
  application:
    name: eureka-server1
eureka:
  instance:
    hostname: peer1
server:
  port: 8761
---
spring:
  profiles: peer2
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: peer2
server:
  port: 8762