eureka:
  client:
    service-url:
      defaultZone: http://172.17.15.173:8761/eureka, http://172.17.15.173:8762/eureka
  server:
    enable-self-preservation: false
---
spring:
  profiles: peer1
  application:
    name: eureka-server1
server:
  port: 8761
eureka:
  instance:
#    hostname: licongchun
    prefer-ip-address: true
---
spring:
  profiles: peer2
  application:
    name: eureka-server2
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
#    hostname: licongchun