eureka:
  client:
    service-url:
      defaultZone: http://106.15.230.133:8761/eureka, http://106.15.230.133:8762/eureka
---
spring:
  profiles: peer1
  application:
    name: eureka-server1
eureka:
  instance:
    prefer-ip-address: true
server:
  port: 8761
---
spring:
  profiles: peer2
  application:
    name: eureka-server2
eureka:
  instance:
    prefer-ip-address: true
server:
  port: 8762